global_frame: enu
initial_pois:
  circle_totems: [-34.408, 50.62, 0]
  dock: [108.05, -1.07, 0]
  entrance_gate: [51.28, -48.69, 0]
  obstacle_course: [-32.803, -83.41, 0]
  ring_challenge: [-20.44, 50.03, 0]
  start_gate: [12.75, 0.433, 0]
  stc: [49.49, -82.65, 0]
